name: CI

on: [push]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v1
      - name: Run the tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
        - if: github.ref == 'refs/heads/master'
        - uses: actions/checkout@v1
        - name: Publish package
          run: npm publish 
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
