name: CI

on: [push]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - id: install-dependencies
      - uses: actions/checkout@v1
        name: Install dependencies
        run: |
          npm install

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - id: test
      - uses: actions/checkout@v1
        name: Run the tests
        run: |
          npm test

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - id: publish
      - uses: actions/checkout@v1
        name: Publish package
        if: github.ref == 'refs/heads/master'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish
